version: "3.8"

volumes:
  rabbitmq_data:
  pgdata: 
  kongadata:

networks:
  kong-net:
    driver: bridge

services:
  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    restart: always
    networks:
      - kong-net
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:2.0.4
    command: "kong migrations bootstrap"
    restart: on-failure
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: password
    depends_on:
      - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:2.0.4
    restart: always
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: password
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-migration
    ports:
      - "8000:8000"
  
  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga
    restart: always
    networks:
        - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: kong
      DB_PASSWORD: password
      DB_DATABASE: konga_db
    depends_on:
      - kong
    ports:
      - "1337:1337"
    volumes:
      - kongadata:/app/kongadata

  ####################################
  # stock_info : The stock_info microservice
  ####################################
  stock_info:
    build:
      context: ./
      dockerfile: stock_info.Dockerfile
    image: markytan/stock_info:esd
    restart: always
    networks:
      - kong-net
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/stock_infoDB
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"

  ####################################
  # stock_pref : The stock_pref microservice
  ####################################
  stock_pref:
    build:
      context: ./
      dockerfile: stock_pref.Dockerfile
    image: markytan/stock_pref:esd
    restart: always
    networks:
      - kong-net
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/stock_prefDB
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"

  ####################################
  # trading_acc : The trading_acc microservice
  ####################################
  trading_acc:
    build:
      context: ./
      dockerfile: trading_acc.Dockerfile
    image: markytan/trading_acc:esd
    restart: always
    networks:
      - kong-net
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/trading_accDB
      PYTHONUNBUFFERED: 1
    ports:
      - "5004:5004"

  ####################################
  # user_info : The user_info microservice
  ####################################
  user_info:
    build:
      context: ./
      dockerfile: user_info.Dockerfile
    image: markytan/user_info:esd
    restart: always
    networks:
      - kong-net
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/userDB
      PYTHONUNBUFFERED: 1
    ports:
      - "5006:5006"

  ####################################
  # user_stock : The user_stock microservice
  ####################################
  user_stock:
    build:
      context: ./
      dockerfile: user_stock.Dockerfile
    image: markytan/user_stock:esd
    restart: always
    networks:
      - kong-net
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/user_stockDB
      PYTHONUNBUFFERED: 1
    ports:
      - "5007:5007"

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    networks:
      - kong-net
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
      
  #################################################
  # email_notification : The email_notification microservice
  #################################################
  email_notification:
    build:
      context: ./
      dockerfile: email_notification.Dockerfile
    image: markytan/email_notification:esd
    restart: always
    networks:
      - kong-net
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###################################
  # Error: The Error microservice
  ###################################
  error:
    build:
      context: ./
      dockerfile: error.Dockerfile
    image: markytan/error:esd
    restart: always
    networks:
      - kong-net
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###############################################
  # trade_log: The trade_log microservice
  ###############################################
  trade_log:
    build:
      context: ./
      dockerfile: trade_log.Dockerfile
    image: markytan/trade_log:esd
    restart: always
    networks:
      - kong-net
    depends_on:
      - rabbitmq
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/trade_logDB
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"

  ###############################################
  # transaction_log: The transaction_log microservice
  ###############################################
  transaction_log:
    build:
      context: ./
      dockerfile: transaction_log.Dockerfile
    image: markytan/transaction_log:esd
    restart: always
    networks:
      - kong-net
    depends_on:
      - rabbitmq
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/transaction_logDB
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
    ports:
      - "5005:5005"

  ###############################################
  # place_trade: The place_trade microservice
  ###############################################
  place_trade:
    build:
      context: ./
      dockerfile: place_trade.Dockerfile
    image: markytan/place_trade:esd
    restart: always
    networks:
      - kong-net
    depends_on:
      - user_info
      - trading_acc
      - stock_info
      - error
      - trade_log
      - email_notification
      - user_stock
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      user_info_URL: http://user_info:5006/account
      trading_acc_URL: http://trading_acc:5004/trading_acc
      stock_info_URL : http://stock_info:5001/stock_info
      user_stock_URL : http://user_stock:5007/user_stock/buy
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"

  ###############################################
  # make_deposit: The make_deposit microservice
  ###############################################
  make_deposit:
    build:
      context: ./
      dockerfile: make_deposit.Dockerfile
    image: markytan/make_deposit:esd
    restart: always
    networks:
      - kong-net
    depends_on:
      - user_info
      - trading_acc
      - error
      - email_notification
      - transaction_log
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      user_info_URL: http://user_info:5006/account/email
      trading_acc_URL: http://trading_acc:5004/trading_acc/plus
      PYTHONUNBUFFERED: 1
    ports:
      - "5101:5101"
  
  
